channels:
  - conda-forge

dependencies:
  - jupyterlab
  - ipympl
  - jupyter_bokeh

  - python ~=3.11
  - emsarray ~=0.6.1
  - numpy ~=1.26.0
  - xarray ~=2023.09
  - bokeh ~=3.1.1
  - cartopy >=0.21.1
  - matplotlib >=3.5.2
  - scipy
  - ffmpeg
